<!-- META -->
<title>ClimateView</title>
<meta charset="utf-8">

<!-- CSS -->
<link href='http://fonts.googleapis.com/css?family=Lato:100,400' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:100,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/css/style.css" title="main styles" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<!-- JS -->
<script src="/js/frameworks/jquery.js"></script>
<script src="/js/frameworks/jqease.js"></script>
<script src="/js/frameworks/msgbox.js"></script>
<script src="/js/frameworks/customEvent.js"></script>
<script src="/js/frameworks/maupload.js"></script>

<!-- Highchart JS -->
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<!-- Site Code -->
<script src="/js/app.js"></script>
<script src="/js/pcpChart.js"></script>
<script src="/js/chdChart.js"></script>
<script src="/js/tpChart.js"></script>
<script src="/js/loginBox.js"></script>
<script src="/js/dataBox.js"></script>
<script src="/js/main.js"></script>
