<div id = "loginBox">
	<div id = "loginContainer">
		<div id = "credentialsContainer">
			<div id = "placeholder"></div>
			<div id = "loginSubcontainer">
				<div class = "credential"><span class = "prompt">Username:</span><input id = "username" type="text"/></div>
				<div class = "credential"><span class = "prompt">Service Code:</span><input id = "password" type="password"/></div>
			</div>
			<div id = "requestContainer">
				<div class = "credential"><span class = "prompt">Email:</span><input id = "email" type="text"/></div>
				<div class = "credential"><span class = "prompt">First Name:</span><input id = "firstName" type="text"/></div>
				<div class = "credential"><span class = "prompt">Last Name:</span><input id = "lastName" type="text"/></div>
				<div class = "credential"><span class = "prompt">Organization:</span><input id = "organization" type="text"/></div>
			</div>				
		</div>
		<input id = "loginAndRequestButton" type = "button" value="Login" />
		<span id = "request">Request Account</span>	
	</div>
</div>